services:
  earthquake_data_layer:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "${DATA_LAYER_PORT}:${DATA_LAYER_PORT}"
    environment:
      - INTEGRATION_TEST=true
      - DATA_LAYER_ENDPOINT=${DATA_LAYER_ENDPOINT}
      - DATA_LAYER_PORT=${DATA_LAYER_PORT}
      - LOG_LEVEL=ERROR
