name: CD-Deploy
on:
  pull_request:
    branches:
      - 'prod'

jobs:
    release:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: release latest version to hub
        run: |
          pwd
          ls
          cat Makefile
          make release
